[[main]]
  name = "Início"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Sobre"
  pageRef = "/about/"
  weight = 20

[[main]]
  name = "Red Team"
  pageRef = "categories/red-team/"
  weight = 30

[[main]]
  name = "Blue Team"
  pageRef = "categories/blue-team/"
  weight = 50

[[main]]
  name = "Curriculo"
  pageRef = "/cv/"
  weight = 50
